"""Discovery and native materialization for portable Agent Skills."""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
from pathlib import Path, PurePosixPath, PureWindowsPath
import re

from .adapters.base import AdapterContext, AgentAdapter
from .adapters.rendered import safe_current_hash, target_root_for
from .model import Ownership
from .plan import WriteOperation
from .portability import lint_skill, parse_portable_skill_frontmatter


_AGENT_ID = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


@dataclass(frozen=True)
class PortableSkill:
    name: str
    description: str
    root: Path
    source_sha256: str


def discover_portable_skills(root: Path) -> tuple[PortableSkill, ...]:
    """Discover safe, valid portable skills immediately below *root*."""
    root = Path(root)
    if not root.exists():
        return ()
    if not root.is_dir() or root.is_symlink():
        raise ValueError(f"portable skill root is unsafe: {root}")

    skills: list[PortableSkill] = []
    try:
        candidates = sorted(root.iterdir(), key=lambda path: path.name.casefold())
    except OSError as error:
        raise ValueError(f"cannot read portable skill root: {root}") from error

    for candidate in candidates:
        if candidate.is_symlink():
            raise ValueError(f"portable skill path is symlinked: {candidate}")
        if not candidate.is_dir():
            continue
        diagnostics = lint_skill(candidate)
        if diagnostics:
            details = "; ".join(
                f"{item.code}: {item.message}" for item in diagnostics
            )
            raise ValueError(f"invalid portable skill {candidate}: {details}")
        try:
            source = candidate.joinpath("SKILL.md").read_text(encoding="utf-8")
            name, description, _ = parse_portable_skill_frontmatter(source)
        except (OSError, UnicodeError, ValueError) as error:
            raise ValueError(f"invalid portable skill {candidate}") from error
        if name != candidate.name:
            raise ValueError(
                f"invalid portable skill {candidate}: name must match directory"
            )
        files = _skill_files(candidate)
        skills.append(
            PortableSkill(
                name=name,
                description=description,
                root=candidate,
                source_sha256=_skill_hash(candidate, files),
            )
        )
    return tuple(skills)


def render_native_skill_wrapper(
    skill: PortableSkill,
    agent_id: str,
    canonical_path: Path,
) -> bytes:
    """Render a metadata-only native wrapper pointing at canonical skill files."""
    if _AGENT_ID.fullmatch(agent_id) is None:
        raise ValueError("agent id must be kebab-case")
    canonical = canonical_path.as_posix()
    if not (
        PurePosixPath(canonical).is_absolute()
        or PureWindowsPath(canonical).is_absolute()
    ):
        raise ValueError("canonical skill path must be absolute")
    canonical_root = canonical.replace("\\", "/").rstrip("/")
    content = (
        "---\n"
        f"name: {skill.name}\n"
        f"description: {skill.description}\n"
        "---\n"
        "<!-- Generated by agent-workflow. Do not edit. -->\n"
        f"# source-sha256: {skill.source_sha256}\n\n"
        "Read the canonical `SKILL.md` completely at "
        f"`{canonical_root}/SKILL.md` before taking action.\n"
        f"Then read `{canonical_root}/overlays/{agent_id}.md` when it exists.\n"
        "Resolve every referenced resource relative to the canonical skill "
        "root above.\n"
    )
    return content.encode("utf-8")


def plan_skill_install(
    adapter: AgentAdapter,
    context: AdapterContext,
    skills: tuple[PortableSkill, ...],
) -> tuple[WriteOperation, ...]:
    """Plan canonical skill writes and adapter-specific native wrappers."""
    manifest = getattr(adapter, "manifest", None)
    if manifest is None:
        raise ValueError(f"adapter {adapter.id} has no skill manifest")

    canonical_parent = context.neutral_root / "skills"
    scope_root = target_root_for(context)
    operations: list[WriteOperation] = []
    for skill in sorted(skills, key=lambda item: item.name.casefold()):
        canonical_root = canonical_parent / skill.name
        if not _same_path(skill.root, canonical_root):
            for source in _skill_files(skill.root):
                relative = source.relative_to(skill.root).as_posix()
                target_path = f"skills/{skill.name}/{relative}"
                target = context.neutral_root.joinpath(*target_path.split("/"))
                operations.append(
                    WriteOperation.from_bytes(
                        root_id="neutral",
                        path=target_path,
                        content=source.read_bytes(),
                        expected_sha256=safe_current_hash(
                            target, context.neutral_root
                        ),
                        ownership=Ownership.CANONICAL,
                    )
                )

        for location in manifest.for_scope(context.scope).skill_locations:
            if location.mode != "wrapper":
                continue
            wrapper_path = (
                f"{location.path}/{skill.name}/SKILL.md"
            )
            target = scope_root.joinpath(*wrapper_path.split("/"))
            operations.append(
                WriteOperation.from_bytes(
                    root_id="scope",
                    path=wrapper_path,
                    content=render_native_skill_wrapper(
                        skill,
                        agent_id=adapter.id,
                        canonical_path=canonical_root,
                    ),
                    expected_sha256=safe_current_hash(target, scope_root),
                    ownership=Ownership.GENERATED,
                )
            )
    return tuple(
        sorted(
            operations,
            key=lambda operation: (
                operation.root_id,
                operation.path.casefold(),
                operation.path,
            ),
        )
    )


def _skill_files(root: Path) -> tuple[Path, ...]:
    files: list[Path] = []
    try:
        entries = sorted(
            root.rglob("*"),
            key=lambda path: path.relative_to(root).as_posix(),
        )
    except OSError as error:
        raise ValueError(f"cannot read portable skill: {root}") from error
    for entry in entries:
        if entry.is_symlink():
            raise ValueError(f"portable skill resource is symlinked: {entry}")
        if entry.is_file():
            files.append(entry)
        elif not entry.is_dir():
            raise ValueError(f"portable skill resource is unsafe: {entry}")
    return tuple(files)


def _skill_hash(root: Path, files: tuple[Path, ...]) -> str:
    digest = hashlib.sha256()
    for source in files:
        relative = source.relative_to(root).as_posix()
        digest.update(relative.encode("utf-8"))
        digest.update(b"\0")
        digest.update(source.read_bytes())
    return digest.hexdigest()


def _same_path(left: Path, right: Path) -> bool:
    try:
        return left.resolve(strict=True) == right.resolve(strict=True)
    except OSError:
        return left.resolve(strict=False) == right.resolve(strict=False)
